import random
class Cat:
    def __init__(self, name, age, color):
        self.name = name
        self.age = age
        self.color = color
        self.energy = 100
        self.hunger = 0
    def sleep(self):
        self.energy += random.randint(5, 15)
        print(f"{self.name} is sleeping. Energy: {self.energy}")
    def eat(self):
        self.hunger -= random.randint(5, 15)
        print(f"{self.name} is eating. Hunger: {self.hunger}")
    def play(self):
        if self.energy >= 10:
            self.energy -= random.randint(5, 15)
            self.hunger += random.randint(5, 15)
            print(f"{self.name} is playing. Energy: {self.energy}, Hunger: {self.hunger}")
        else:
            print(f"{self.name} is too tired to play. Energy: {self.energy}")
my_cat = Cat(name="Whiskers", age=2, color="gray")
my_cat.sleep()
my_cat.eat()
my_cat.play()
